---

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check Links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: "no"
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: "yes"
