# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/markdown.tftpl.yml

---

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/${checkout.owner}/${checkout.repository}/releases/tag/${checkout.version}
      - name: Checkout Repository
        uses: "${checkout.owner}/${checkout.repository}@${checkout.sha}" # ref: `${checkout.ref}`
        with:
          fetch-depth: 1

      # see https://github.com/${markdown.owner}/${markdown.repository}/releases/tag/${markdown.version}
      - name: Check Links in Markdown files
        uses: "${markdown.owner}/${markdown.repository}@${markdown.sha}" # ref: `${markdown.ref}`
        with:
          check-modified-files-only: no
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: yes
