# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/scorecard.tftpl.yml

---

name: "Security: OpenSSF Scorecard"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  workflow:
    # only run if workflows are enabled
    if: $${{ vars.ENABLE_WORKFLOWS == 'true' }}

    name: OpenSSF Scorecard

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # see https://github.com/${checkout.owner}/${checkout.repository}/releases/tag/${checkout.version}
      - name: Checkout Repository
        uses: "${checkout.owner}/${checkout.repository}@${checkout.sha}" # ref: `${checkout.ref}`
        with:
          fetch-depth: 1

      # see https://github.com/${scorecard.owner}/${scorecard.repository}/releases/tag/${scorecard.version}
      - name: Lint Code with Snyk
        uses: "${scorecard.owner}/${scorecard.repository}@${scorecard.sha}" # ref: `${scorecard.ref}`
        with:
          publish_results: true
          result_file: "scorecard.sarif"
          result_format: sarif

      # see https://github.com/${codeql_upload.owner}/${codeql_upload.repository}/releases/tag/${codeql_upload.version}
      - name: Upload OpenSSF Scorecard results to GitHub Code Scanning
        uses: "${codeql_upload.owner}/${codeql_upload.repository}@${codeql_upload.sha}" # ref: `${codeql_upload.ref}`
        with:
          sarif_file: "scorecard.sarif"

  workflow-inactive:
    # only run if workflows are disabled
    if: $${{ vars.ENABLE_WORKFLOWS != 'true' }}

    name: Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Display Workflow Status
        run: echo "::warning ::Workflow is not currently active. Check if `ENABLE_WORKFLOWS` is set to `true`."
