# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/snyk-iac.tftpl.yml

---

name: "Security: Snyk IaC"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  workflow:
    # only run if workflows are enabled
    if: $${{ vars.ENABLE_WORKFLOWS == 'true' }}

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: "$${{ github.workflow }}-$${{ github.ref }}"
      cancel-in-progress: true

    name: Snyk IaC

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      security-events: write

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # see https://github.com/${checkout.owner}/${checkout.repository}/releases/tag/${checkout.version}
      - name: Checkout Repository
        uses: "${checkout.owner}/${checkout.repository}@${checkout.sha}" # ref: `${checkout.ref}`
        with:
          fetch-depth: 1

      # see https://github.com/${snyk_iac.owner}/${snyk_iac.repository}/releases/tag/${snyk_iac.version}
      - name: Lint Code with Snyk
        uses: "${snyk_iac.owner}/${snyk_iac.repository}@${snyk_iac.sha}" # ref: `${snyk_iac.ref}`
        env:
          SNYK_ORG: "$${{ vars.SNYK_ORG }}"
          SNYK_TOKEN: "$${{ secrets.SNYK_TOKEN }}"
        with:
          # scan all code in the root of the repository
          file: "./"
          # see https://docs.snyk.io/products/snyk-infrastructure-as-code/snyk-cli-for-infrastructure-as-code/iac-ignores-using-the-.snyk-policy-file#policy-flags-and-policy-file-notes
          args: "--policy-path='.snyk'"
          sarif: true

      # see https://github.com/${codeql_upload.owner}/${codeql_upload.repository}/releases/tag/${codeql_upload.version}
      - name: Upload Snyk IaC results to GitHub Code Scanning
        uses: "${codeql_upload.owner}/${codeql_upload.repository}@${codeql_upload.sha}" # ref: `${codeql_upload.ref}`
        with:
          sarif_file: "snyk.sarif"

  workflow-inactive:
    # only run if workflows are disabled
    if: $${{ vars.ENABLE_WORKFLOWS != 'true' }}

    name: Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Display Workflow Status
        # shellcheck disable=SC2006
        run: echo "::notice title='Workflow is not currently active'::'Check if `ENABLE_WORKFLOWS` is set to `true`.'"
