---
name: "Code Quality: Terraform"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Initialize Terraform for Module
        run: terraform init
        env:
          working-dir: "./"

      - name: Format Terraform code for Module
        run: terraform fmt -check -recursive
        env:
          working-dir: "./"
