# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/terraform-docs.tftpl.yml

---
name: "Documentation: terraform-docs"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # see https://github.com/${checkout.owner}/${checkout.repository}/releases/tag/${checkout.version}
      - name: Checkout Repository
        uses: "${checkout.owner}/${checkout.repository}@${checkout.version}" # ${checkout.version}
        with:
          ref: "$${{ github.event.pull_request.head.ref }}"
          fetch-depth: 1

      # see https://github.com/${terraform_docs.owner}/${terraform_docs.repository}/releases/tag/${terraform_docs.version}
      - name: Render documentation for repository and push changes back to branch
        uses: "${terraform_docs.owner}/${terraform_docs.repository}@${terraform_docs.version}" # ${terraform_docs.version}
        with:
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: inject"
          git-push: true
          working-dir: "./"
