---

# allow inline overrides (e.g.: `# hadolint ignore=DL1234`)
disable-ignore-pragma: false

# exit with failure status code when this severity level is reached
failure-threshold: warning

# output format
format: checkstyle

# exit with failure status code when a rule fails
no-fail: false

# list of Docker Registries that may appear in `FROM` statements
trustedRegistries:
  - "*.docker.io"
  - "*.ghcr.io"
