# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/markdown.tftpl.yml

---

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/upload-artifact/releases/tag/v3.1.2
      - name: Checkout Repository
        uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce" # ref: `tags/v3.1.2`
        with:
          fetch-depth: 1

      # see https://github.com/gaurav-nelson/github-action-markdown-link-check/releases/tag/1.0.15
      - name: Check Links in Markdown files
        uses: "gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec" # ref: `tags/1.0.15`
        with:
          check-modified-files-only: no
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: yes
