# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/superlinter.tftpl.yml

---

name: "Code Quality: Super-Linter"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  workflow:
    # only run if workflows are enabled
    if: ${{ vars.ENABLE_WORKFLOWS == 'true' }}

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: true

    name: Super-Linter

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      statuses: write

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # see https://github.com/actions/checkout/releases/tag/v3.5.2
      - name: Checkout Repository
        uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # ref: `tags/v3.5.2`
        with:
          # full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # see https://github.com/super-linter/super-linter/releases/tag/v5.0.0
      - name: Lint Code with Super-Linter
        uses: "super-linter/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7" # ref: `tags/v5.0.0`
        env:
          # see https://github.com/github/super-linter#environment-variables
          CSS_FILE_NAME: ".stylelintrc.json"
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          DOCKERFILE_HADOLINT_FILE_NAME: ".hadolint.yml"
          GITHUB_CUSTOM_API_URL: "https://api.github.com"
          GITHUB_DOMAIN: "github.com"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          MARKDOWN_CONFIG_FILE: ".markdown-lint.yml"
          MULTI_STATUS: true
          NATURAL_LANGUAGE_CONFIG_FILE: ".textlint.yml"
          SUPPRESS_POSSUM: true
          TERRAFORM_TFLINT_CONFIG_FILE: ".tflint.hcl"
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_CPP: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CLOJURE: false
          VALIDATE_CLOUDFORMATION: false
          VALIDATE_COFFEESCRIPT: false
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GHERKIN: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: false
          VALIDATE_GO: true
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_GROOVY: false
          VALIDATE_HTML: true
          VALIDATE_JAVA: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSCPD_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: true
          VALIDATE_JS: false
          VALIDATE_KOTLI: false
          VALIDATE_KOTLIN_ANDROI: false
          VALIDATE_KUBERNETES_KUBECONFOR: false
          VALIDATE_LATE: false
          VALIDATE_LU: false
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_OPENAPI: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_PHP_BUILTIN: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PROTOBUF: false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_R: false
          VALIDATE_RAKU: false
          VALIDATE_RUBY: false
          VALIDATE_SCALAFMT: false
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_SNAKEMAKE_LINT: false
          VALIDATE_SNAKEMAKE_SNAKEFMT: false
          VALIDATE_STATES: false
          VALIDATE_SQL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_TEKTON: false
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_TERRAGRUNT: false
          VALIDATE_TSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: ".yaml-lint.yml"
          YAML_ERROR_ON_WARNING: true

  workflow-inactive:
    # only run if workflows are disabled
    if: ${{ vars.ENABLE_WORKFLOWS != 'true' }}

    name: Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Display Workflow Status
        run: echo "::warning ::Workflow is not currently active. Check if `ENABLE_WORKFLOWS` is set to `true`."
