---
name: "Code Quality: TFLint"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          working-dir: "./"

      - name: Initialize TFLint
        run: tflint --init "./"

      - name: Run TFLint
        run: tflint --format=compact "./"
